name: simple_icons
description: The Simple Icon pack available as Flutter Icons. Provides over 1500 Free SVG icons for popular brands.
version: 15.4.0
homepage: https://teavelopment.com/
repository: https://github.com/jlnrrg/simple_icons
environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  alchemist: ^0.7.0
  flutter_test:
    sdk: flutter
  recase: ^4.1.0
  unorm_dart: ^0.3.0
  xml: ^6.5.0
screenshots:
  - description: Simple Icons Overview
    path: assets/simple_icons_overview.png
flutter:
  fonts:
    - family: SimpleIcons
      fonts:
        - asset: fonts/SimpleIcons.ttf
